import Nav from './(layout)/nav/Nav'
import { DataGet } from './context/DataContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Candleaf E-Commerce Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataGet>
        <Nav />
        {children}
        </DataGet>
        </body>
    </html>
  )
}
